name: Scan Virus

on:
  push:
    branches:
      - main

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 5


    steps:
      - uses: actions/checkout@v1

      # https://docs.clamav.net/manual/Installing/Docker.html
      # https://clamav-jp.osdn.jp/jdoc/clamav.html#c3.2.1

      # test virus
      # https://downloadcenter.trendmicro.com/index.php?regs=jp&prodid=1424

      - name: scan clamav
        id: scan_clamav
        run: |
          scandir=$(pwd)
          docker run \
            --rm \
            --mount type=bind,source=$scandir,target=/scandir \
            --mount type=bind,source=/tmp,target=/var/lib/clamav \
            clamav/clamav:0.105 \
            freshclam --on-update-execute="clamscan -r --log=/tmp/result.log /scandir"
            echo "[result]"
            cat /tmp/result.log

            # freshclam --on-update-execute="clamscan /scandir"

      - name: Create issue
        if: ${{ steps.scan_clamav.outcome == 'failure' }}
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "virus"
          title: "virus check failed !"
          body: |
            $(cat /tmp/result.log)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
