name: Scan Virus

on:
  push:
    branches:
      - main

# 空文字だと全フォルダを対象
env:
  SCAN_DIR : "subdir"

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 5


    steps:
      - uses: actions/checkout@v1

      # https://docs.clamav.net/manual/Installing/Docker.html
      # https://clamav-jp.osdn.jp/jdoc/clamav.html#c3.2.1

      # test virus
      # https://downloadcenter.trendmicro.com/index.php?regs=jp&prodid=1424

      - name: scan clamav
        id: scan_clamav
        run: |
          scandir=$(pwd)/${{env.SCAN_DIR}}
          docker run \
            --rm \
            --mount type=bind,source=$scandir,target=/scandir \
            --mount type=bind,source=/tmp,target=/tmp \
            clamav/clamav:0.105 \
            freshclam --on-update-execute="clamscan -r -l /tmp/result.log /scandir"
        shell: bash -xe

      - name: check result
        id: check_result
        run: |
            echo "[scan result]"
            cat /tmp/result.log

            failed_check=$(cat /tmp/result.log | grep FOUND | wc -m | awk '{print $1}')

            # FOUNDが1件でもあったらjobを失敗させる
            if [ ${failed_check} -ne 0 ]; then
              echo "*****************************"
              echo "[Failed] virus is existed !!!"
              echo "*****************************"
              exit 1
            fi 

      - name: Create issue
        if: failure() && steps.check_result.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
          --title "[Failed] virus is existed !!!" \
          --label virus \
          --body-file /tmp/result.log
