name: Scan Virus

on:
  push:
    branches:
      - main

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 300


    steps:
      - uses: actions/checkout@v1

      - name: display info
        run: |
          ls $(pwd)

      - name: install clamav
        run: |
          echo "[Install clamav]"
          sudo apt-get install clamav clamav-daemon
          echo "[Start clamav-daemon]"
          sudo systemctl start clamav-daemon.service
          sudo systemctl status clamav-daemon.service
          echo "[Start clamav-freshclam]"
          sudo systemctl start clamav-freshclam.service
          sudo systemctl status clamav-freshclam.service
          echo "[Update pattern]"
          sudo freshclam

      - name: scan
        run: |
          scandir=$(pwd)
          sudo clamdscan -r $scandir

