name: Scan Virus

on:
  push:
    branches:
      - main

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 300


    steps:
      - uses: actions/checkout@v1

      - name: display info
        run: |
          echo $GITHUB_PATH
          ls $GITHUB_PATH
          pwd

      - name: install clamav
        run: |
          sudo apt-get install clamav clamav-daemon
          sudo systemctl start clamav-daemon.service
          sudo systemctl start clamav-daemon.service 

