name: Scan Virus

on:
  push:
    branches:
      - main

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 5


    steps:
      - uses: actions/checkout@v1

      # https://docs.clamav.net/manual/Installing/Docker.html
      # https://clamav-jp.osdn.jp/jdoc/clamav.html#c3.2.1
      - name: run clamav
        run: |
          scandir=$(pwd)
          docker run \
            --rm \
            --mount type=bind,source=$scandir,target=/scandir \
            --mount type=bind,source=/tmp,target=/var/lib/clamav \
            clamav/clamav:0.105 \
            freshclam --on-update-execute="clamscan /scandir"
