name: Scan Virus (use action)

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      scandir:
        description: 'Input scan dir'
        required: false

jobs:
  scan-virus:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - name: scan virus by clamav
        id: scan-virus
        uses: ./.github/actions/scanvirus
        with:
          scan-dir: $(pwd)/${{ github.event.inputs.scandir }}

      - name: Create issue
        if: failure() && steps.scan-virus.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
          --title "[Failed] virus is existed !!!" \
          --label virus \
          --body-file ${{ steps.scan-virus.outputs.report-file }}
        shell: bash